# Generated by Django 3.2.2 on 2021-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farmName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
