# Generated by Django 3.2.2 on 2021-05-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmProduct', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFarmer',
            field=models.BooleanField(default=False),
        ),
    ]
