# Generated by Django 3.1.4 on 2021-06-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmProduct', '0006_auto_20210609_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/dummy.png', null=True, upload_to='product_img'),
        ),
    ]
