# Generated by Django 3.1.4 on 2021-07-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmProduct', '0007_auto_20210630_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
