# Generated by Django 3.1.4 on 2021-09-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmProduct', '0015_auto_20210901_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
    ]
