# Generated by Django 3.1.4 on 2021-09-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmProduct', '0016_remove_productimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
