# Generated by Django 3.1.4 on 2021-09-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmProduct', '0017_auto_20210901_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
