# Generated by Django 3.1.4 on 2021-07-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='reads',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
