# Generated by Django 3.1.4 on 2021-07-23 05:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0004_auto_20210723_0524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogVidoes',
        ),
    ]
