# Generated by Django 3.1.4 on 2021-07-27 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_blogvidoes_lenchar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlogs',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image', models.ImageField(upload_to='blog/vlog/images/')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.vlogs')),
            ],
        ),
    ]
