# Generated by Django 3.1.4 on 2021-07-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogs',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
