# Generated by Django 3.1.4 on 2021-07-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_vlogs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='vlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='story.vlogs'),
        ),
    ]
