# Generated by Django 3.1.4 on 2021-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_auto_20210727_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vlogs',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vlogs',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vlogs',
            name='url_field',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vlogs',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
