# Generated by Django 3.1.4 on 2021-07-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_auto_20210727_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlogs',
            old_name='name',
            new_name='title',
        ),
    ]
