# Generated by Django 3.1.4 on 2021-07-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_auto_20210727_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvidoes',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
