# Generated by Django 3.1.4 on 2021-08-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_blogvidoes_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlogs',
            name='views',
        ),
        migrations.AlterField(
            model_name='vlogs',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
