# Generated by Django 3.1.4 on 2021-08-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_auto_20210806_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogs',
            name='isLike',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
