# Generated by Django 3.1.4 on 2021-09-07 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0017_vlogs_islike'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommingSoonExciment',
            fields=[
                ('isexcited', models.BooleanField(default=False)),
                ('isnotexcited', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='vlogs',
            old_name='like',
            new_name='numexcited',
        ),
        migrations.RemoveField(
            model_name='vlogs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vlogs',
            name='isLike',
        ),
        migrations.RemoveField(
            model_name='vlogs',
            name='url_field',
        ),
        migrations.AddField(
            model_name='vlogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/'),
        ),
        migrations.AddField(
            model_name='vlogs',
            name='numnoexcited',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='commingsoonexciment',
            name='vlogs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.vlogs'),
        ),
    ]
