export const BLOG_VIDOE_REQUEST = 'BLOG_VIDOE_REQUEST'
export const BLOG_VIDOE_SUCCESS = 'BLOG_VIDOE_SUCCESS'
export const BLOG_VIDOE_FAIL    =    'BLOG_VIDOE_FAIL'


export const BLOG_VIDOE_DETAILS_REQUEST = 'BLOG_VIDOE_DETAILS_REQUEST'
export const BLOG_VIDOE_DETAILS_SUCCESS = 'BLOG_VIDOE_DETAILS_SUCCESS'
export const BLOG_VIDOE_DETAILS_FAIL    =    'BLOG_VIDOE_DETAILS_FAIL'
export const BLOG_VIDOE_DETAILS_RESET = 'BLOG_VIDOE_DETAILS_RESET'


export const VLOG_IMAGES_REQUEST = 'VLOG_IMAGES_REQUEST'
export const VLOG_IMAGES_SUCCESS = 'VLOG_IMAGES_SUCCESS'
export const VLOG_IMAGES_FAIL    =    'VLOG_IMAGES_FAIL'



export const VLOG_LIKE_REQUEST = 'VLOG_LIKE_REQUEST'
export const VLOG_LIKE_SUCCESS = 'VLOG_LIKE_SUCCESS'
export const VLOG_LIKE_FAIL = 'VLOG_LIKE_FAIL'
export const VLOG_LIKE_RESET = 'VLOG_LIKE_RESET'