# Generated by Django 3.1.4 on 2021-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay_payment_history',
            name='RazorPay_success_createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
