# Generated by Django 3.1.4 on 2021-08-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210703_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCommisionStatus',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
