# Generated by Django 3.1.4 on 2021-08-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordercommisionstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercommisionstatus',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
