# Generated by Django 3.1.4 on 2021-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210823_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay_payment_history',
            name='createdAt',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
