# Generated by Django 3.1.4 on 2021-08-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210823_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpay_payment_history',
            name='createdAt',
        ),
    ]
