# Generated by Django 3.1.4 on 2021-08-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_razorpay_payment_history_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay_payment_history',
            name='createdAt',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phoneNum',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
